### ISSUE TITLE
Issue in motion planning of the hand

### ISSUE THREAD

**Issue by biancofla** [myyerrol/learning_moveit#3]
Another bug found. Any plan for moving Panda hand fail. Here is a shot of the error.
![screen_3](https://user-images.githubusercontent.com/33801756/44000302-b32be0e0-9e1d-11e8-9821-9eb4ff638df4.png)

**Comment by myyerrol** [comment]
@biancofla You must use the `panda_moveit_config` package I configured because I rewrote the official `panda_description` where the names of the joints and links have all been modified, if you used the official `panda_moveit_config` package, you may have this problem.

**Comment by biancofla** [comment]
Actually, I have only your ```panda_moveit_config``` package built. No one other is present on my system.

**Comment by myyerrol** [comment]
Which file are you `roslaunch`?

**Comment by biancofla** [comment]
```panda_bringup_gazebo_and_moveit.launch```

**Comment by myyerrol** [comment]
Run the following command:
```sh
sudo apt-get install ros-kinetic-follow-joint-trajectory-controller
```

**Comment by biancofla** [comment]
For that name no package is available. Maybe is a problem of missing repo?

**Comment by myyerrol** [comment]
Try to run the following command:
```sh
sudo apt-get install ros-kinetic-position-controllers ros-kinetic-velocity-controllers ros-kinetic-effort-controllers
```

**Comment by biancofla** [comment]
Are already installed.

**Comment by myyerrol** [comment]
If `panda_bringup_gazebo_and_moveit.launch` run normally, you'll see following window:
![screenshot from 2018-08-13 23-23-26](https://user-images.githubusercontent.com/4677346/44041429-56fe1390-9f50-11e8-8c65-8fde7b88ed4e.png)
Did you install `panda_moveit_config` package in your system before by using `apt-get install`? If so, please try again after you have deleted it.

**Comment by biancofla** [comment]
This is the situation of Gazebo and Rviz when I launch ```panda_bringup_gazebo_and_moveit.launch```.
![screen_4](https://user-images.githubusercontent.com/33801756/44084841-24d22f7e-9fb8-11e8-8958-47c7243d3438.png)
![screen_5](https://user-images.githubusercontent.com/33801756/44084848-27d4a6de-9fb8-11e8-88e2-ae9779fadb25.png)
Now, after the switch in Planning Request section from panda_arm to panda_hand, the planning seems works fine, but the execution of planning return this error:
![screen_6](https://user-images.githubusercontent.com/33801756/44084960-719bc64e-9fb8-11e8-814a-107086c61f94.png)

**Comment by myyerrol** [comment]
@biancofla If you explain the problem so clearly at the first time, I will soon know cause of the problem. Well, first of all, look at the contents of `panda_moveit_config/config/controllers.yaml`:
```yaml
controller_list:
  - name: panda_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_arm_1
      - joint_arm_2
      - joint_arm_3
      - joint_arm_4
      - joint_arm_5
      - joint_arm_6
      - joint_arm_7

  # - name: panda_hand_controller
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   default: true
  #   joints:
  #     - joint_finger_l
  #     - joint_finger_r

  # - name: panda_hand_controller
  #   action_ns: gripper_cmd
  #   type: GripperCommand
  #   default: true
  #   parallel: true
  #   joints:
  #     - joint_finger_l
  #     - joint_finger_r
```
As you can see, I have commented the parts of the `panda_hand_controller`. Because the end effector doesn't require motion planning, I just configured the controller in Gazebo, MoveIt can't find the corresponding configuration file when you select the planning group to perform the action, so it's natural to report such an error. **The solution is to uncomment the first block**. It depends on you, anyway, I command directly to control the end effector without motion planning.
